### ISSUE TITLE
Latest version does not start

### ISSUE THREAD

**Issue by YuXiaoCoder** [bifrost-finance/bifrost#1128]
Version: `bifrost-v0.9.90`
Command flag: `/opt/bncmain/core/bifrost --validator --name=BitStack-0 --base-path=/mnt/bncmain/node --chain=bifrost --database=rocksdb --relay-chain-rpc-urls ws://ksm-0.ksm.blocknodehub.com:9944 ws://ksm-1.ksm.blocknodehub.com:9944 ws://ksm-2.ksm.blocknodehub.com:9944 ws://ksm-3.ksm.blocknodehub.com:9944 --execution=wasm --wasm-execution=compiled --trie-cache-size=0 --db-cache=4000 --rpc-port=9944 --unsafe-rpc-external --rpc-methods=unsafe --rpc-cors=all --rpc-max-connections=2000 --port=30333 --state-pruning=archive --blocks-pruning=archive`

error log: 
```log
Error: Input("Error parsing spec file: missing field `relayChain` at line 52182 column 1")
```

**Comment by zekchan** [comment]
Seems like https://github.com/bifrost-finance/bifrost/pull/1127 fixes that

**Comment by YuXiaoCoder** [comment]
@zekchan thank you and when is the new release expected?

**Comment by ark930** [comment]
@YuXiaoCoder  The latest docker image(bifrostnetwork/bifrost:bifrost-v0.9.90-1) fixed this issue.

**Comment by ark930** [comment]
And this release https://github.com/bifrost-finance/bifrost/releases/tag/bifrost-v0.9.90-1

**Comment by YuXiaoCoder** [comment]
@ark930 Thank you very much, it has been upgraded successfully

**Comment by YuXiaoCoder** [comment]
Version: `bifrost-v0.9.90-1`

Command flag:
```bash
/opt/bnc-dmain/core/bifrost --validator --name=BitStack-1 --base-path=/mnt/bnc-dmain/node --chain=/mnt/bnc-dmain/conf/bifrost-polkadot.json --database=rocksdb --relay-chain-rpc-urls ws://dot-0.dot.blocknodehub.com:9944 ws://dot-1.dot.blocknodehub.com:9944 ws://dot-2.dot.blocknodehub.com:9944 ws://dot-3.dot.blocknodehub.com:9944 --execution=wasm --wasm-execution=compiled --trie-cache-size=0 --db-cache=4000 --rpc-port=9944 --unsafe-rpc-external --rpc-methods=unsafe --rpc-cors=all --rpc-max-connections=2000 --port=30333 --state-pruning=archive --blocks-pruning=archive]
```

error log:
```bash
Error: Input("Error parsing spec file: missing field `relayChain` at line 98 column 1")
```

**Comment by YuXiaoCoder** [comment]
@ark930 @zekchan Ran into the same problem again with the polkadot chain

**Comment by ark930** [comment]
@YuXiaoCoder https://raw.githubusercontent.com/bifrost-finance/bifrost/develop/node/service/res/bifrost-polkadot.json

**Comment by YuXiaoCoder** [comment]
Thank you very much, it has been upgraded successfully
