### ISSUE TITLE
Testnet Not showing best and target blocks

### ISSUE THREAD

**Issue by shanithkk** [bifrost-finance/bifrost#1164]
### Description
Parachain not showing target and best in the logs while running the `testnet` of bifrost node.

### Expected Behaviour
Target and synced best and finalised nodes should be shown in logs 

### Screenshot
![MicrosoftTeams-image (15)](https://github.com/bifrost-finance/bifrost/assets/59169878/c9cfeaf5-c05a-43b3-b99a-feda2a3d9a8a)

**Comment by TomatoAres** [comment]
Hello, I need to confirm a few questions first:

* What command did you use to start bifrost?
* What's your relay chain?

I see that the peer of parallel chains is 0, and half of them need to specify the local environment to block
In addition, the parallel chain can only be blocked after the relay chain block synchronization is completed

**Comment by shanithkk** [comment]
Hi @TomatoAres ,
- I'm using the command for testnet node is.  
`--chain=bifrost-kusama-rococo --port=30333 --rpc-port=9947 --prometheus-external --rpc-cors=all --rpc-external --rpc-methods=unsafe --unsafe-rpc-external --name=alice --validator `.

- Relay chain is rococo

Peers are showing zero, and i want to confirm that i need to wait until relay chain fully synced or it will show target and best while relay syncing

**Comment by TomatoAres** [comment]
@shanithkk 
You mentioned that the relay chain Rococo is using Parity's online environment. The relay chain naturally comes with a bootnode, which explains why you are capable of synchronizing data. However, there's no default bootnode in the ﻿bifrost-rococo chainspec, which could be why you can't synchronize.
I'm not entirely sure what your testing purpose is.

* If you're running tests locally, I recommend you start the local relay chain ﻿rococo-local alongside the parachain using ﻿--chain=bifrost-kusama-rococo-local for your tests. This way you won't need to synchronize as much relay chain data, allowing you to see results faster.
* If you're using the online Rococo, you'll need to specify our bootnodes, which are not yet publicly available. Moreover, your tests will likely take a long time to complete.

Furthermore, I recommend using tools like ﻿zombienet or chopsticks to quickly set up your testing environment.

**Comment by shanithkk** [comment]
Hi @TomatoAres, we are building a tool called [dive](https://github.com/HugoByte/DIVE) as same like zombinet, but extended suport like spawning testnet and mainnet nodes. if you can provide the bootnode, i can add in the spec and try it out. 
also can you add this bootnodes in the chain spec will be more helpful.

**Comment by TomatoAres** [comment]
@shanithkk Thank you, we will consider incorporating 'dive' in future usage.

You can test with bootNodes

```
--bootnodes  /dns4/eu.bifrost-rococo.liebi.com/tcp/30333/p2p/12D3KooWFZHpXfK7XKJQEPgvhkC3SzDTJCVHzSp54LYGtYUmvg82 \
--bootnodes  /dns4/eu.bifrost-rococo.liebi.com/tcp/31333/p2p/12D3KooWSuhVMwf76pe2KyDqGGtW11Ab7yhDXfQSZMjEo168pbpR \
--bootnodes  /dns4/eu2.bifrost-rococo.liebi.com/tcp/30333/p2p/12D3KooWCUKdehGqnTpL8MyvbYcuqpnZP43N5Dhw5zypKSUToojA \
--bootnodes  /dns4/eu2.bifrost-rococo.liebi.com/tcp/31333/p2p/12D3KooWKs9Dt4TqFTfGjc7cDvtjRYVUmXF7Fk8HJUn1XgKt7Fje

```

I have add the bootnodes in [code](https://github.com/bifrost-finance/bifrost/pull/1173/commits/60f402fbbcff15272e429a925d27d56297818b46)
