### ISSUE TITLE
Unable to query GLMR ballance

### ISSUE THREAD

**Issue by dudo50** [bifrost-finance/bifrost#1492]
Hello team Bifrost,

We have a problem fetching our GLMR balance on Bifrost.

Could you please take a look into this?

Other assets work just fine, which is strange.

The asset registry shows GLMR under Token2, but the query returns 0 instead of the actual balance.

The wallets also show 0 balance, which could be a chain problem.

![photo](https://github.com/user-attachments/assets/be59c561-4c06-465e-aae3-692719423b09)
![photoo](https://github.com/user-attachments/assets/bb638b6c-389d-400d-b3b0-20d95722dd84)

Thanks!

**Comment by Wsteth** [comment]
> Hello team Bifrost,
> 
> We have a problem fetching our GLMR balance on Bifrost.
> 
> Could you please take a look into this?
> 
> Other assets work just fine, which is strange.
> 
> The asset registry shows GLMR under Token2, but the query returns 0 instead of the actual balance.
> 
> The wallets also show 0 balance, which could be a chain problem.
> 
> ![photo](https://private-user-images.githubusercontent.com/55763425/383117136-be59c561-4c06-465e-aae3-692719423b09.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA4MTExMzcsIm5iZiI6MTczMDgxMDgzNywicGF0aCI6Ii81NTc2MzQyNS8zODMxMTcxMzYtYmU1OWM1NjEtNGMwNi00NjVlLWFhZTMtNjkyNzE5NDIzYjA5LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTA1VDEyNDcxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZmNDY1OTM5NTE0NDdjMGU3MzdmNDk5YWI0YzA2MGI2MzkzODY2NzIxYTAwNzU5MjI2MjdmMWY0ZjhkNjFhMGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.h-_m4bqMgLHJkMkKfdoK5sS_yH1rOFPW3M77uiwcZFI) ![photoo](https://private-user-images.githubusercontent.com/55763425/383117145-bb638b6c-389d-400d-b3b0-20d95722dd84.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA4MTExMzcsIm5iZiI6MTczMDgxMDgzNywicGF0aCI6Ii81NTc2MzQyNS8zODMxMTcxNDUtYmI2MzhiNmMtMzg5ZC00MDBkLWIzYjAtMjBkOTU3MjJkZDg0LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTA1VDEyNDcxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVlZTZhMTVlMjdkYTk1MDM0YjFjMWVmMzQ0NDk0NjQyZDZmNmExYmIxYzM3YTc4NmZlMTQ0YWE3YzliODgxYjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.IA05RvhUy0poYTP-eRws771ZJ_FT0VHgA0kBKcRn3x8)
> 
> Thanks!


Hello friend,
Could you give us some specific infomation(account or some context)?
And did you check the account is correct?

**Comment by dudo50** [comment]
@Wsteth you are totally right! Was a communication error on our side! Everything works well. Sorry for the unnecessary ping!
