### ISSUE TITLE
Node sync failing

### ISSUE THREAD

**Issue by Asubayo** [bifrost-finance/bifrost#1531]
Hello,
I am trying to run a collator node but I am facing some sync issues.

`Nov 30 03:02:55 ns5009280 bifrost[1069881]: 2024-11-30 03:02:55 [Parachain🌈] 💔 Error importing block 0xe34b3e8cc76f13447ab6ad102f85b362543490aef90ca808147071b74e2ebaca: consensus error: Import failed: Runtime Ethereum block not found, rejecting`

I am stuck on block #5,331,573

I run the release v 0.15.1

This is my command line

`/home/sydney/bifrost-v0.15.1/bifrost-bifrost-v0.15.1/target/release/bifrost --collator --chain "/home/sydney/bifrost-v0.15.1/bifrost-bifrost-v0.15.1/bifrost-polkadot.json" --telemetry-url "wss://telemetry.polkadot.io/submit/ 0" --name My-node --base-path "/home/sydney/bifrost-v0.15.1/bifrost-bifrost-v0.15.1/target/release/data" --node-key 39f1ea7399f1ebaa774beb5e6e4df9a24b1a974d8d7ebbfa65facb45bf3131ae --rpc-port 9933 --port 30333 --prometheus-external --state-cache-size 0 -- --chain polkadot`

Found this related issue https://github.com/polkadot-evm/frontier/issues/223

What could I do to bypass that sync issue ?

**Comment by TomatoAres** [comment]
I encountered the same problem, but the block height at which it occurred is different. The specific reason is unknown. However, after deleting the relay chain data and restarting the synchronization, this problem no longer exists.

**Comment by hqwangningbo** [comment]
Answered in Discord.
