### ISSUE TITLE
can't build by error blow

### ISSUE THREAD

**Issue by TerenceClark** [bifrost-finance/bifrost#196]
error: failed to resolve patches for `https://github.com/rust-lang/crates.io-index`

Caused by:
  failed to load source for dependency `zenlink-protocol`

Caused by:
  Unable to update ssh://git@github.com/bifrost-finance/Zenlink-DEX-Module?branch=polkadot-v0.9.8#8e9e8708

**Comment by yrong** [comment]
currently we have some dex features depending on zenlink-protocol which is not open source yet. If only take a try you can start docker container following the readme

**Comment by sawvox** [comment]
@yrong are there any plans on open sourcing that code yet?

**Comment by ark930** [comment]
@sawvox `zenlink-protocol` is an open source project now, feel free to compile with it.
