### ISSUE TITLE
Critical database error "Corruption: Bad table magic number: expected 9863518390377041911, found 0"

### ISSUE THREAD

**Issue by romanuz** [bifrost-finance/bifrost#28]
Full log message is provided below:

2020-08-01 15:03:57 ⛓  Native runtime: bifrost-12 (bifrost-node-1.tx1.au1)

====================

Version: 0.4.0

   0: sp_panic_handler::set::{{closure}}
   1: std::panicking::rust_panic_with_hook
             at rustc/5c1f21c3b82297671ad3ae1e8c942d2ca92e84f2/src/libstd/panicking.rs:490
   2: rust_begin_unwind
             at rustc/5c1f21c3b82297671ad3ae1e8c942d2ca92e84f2/src/libstd/panicking.rs:388
   3: std::panicking::begin_panic_fmt
             at rustc/5c1f21c3b82297671ad3ae1e8c942d2ca92e84f2/src/libstd/panicking.rs:342
   4: <sp_database::kvdb::DbAdapter<D> as sp_database::Database<H>>::get
   5: sc_finality_grandpa::aux_schema::load_persistent
   6: sc_finality_grandpa::block_import
   7: sc_service::builder::ServiceBuilder<TBl,TRtApi,TCl,TFchr,TSc,TImpQu,TFprb,TFpp,TExPool,TRpc,Backend>::with_import_queue
   8: node_cli::service::new_full
   9: sc_cli::runner::Runner<C>::run_node
  10: node_cli::command::run
  11: bifrost_node::main
  12: std::rt::lang_start::{{closure}}
  13: std::rt::lang_start_internal::{{closure}}
             at rustc/5c1f21c3b82297671ad3ae1e8c942d2ca92e84f2/src/libstd/rt.rs:52
      std::panicking::try::do_call
             at rustc/5c1f21c3b82297671ad3ae1e8c942d2ca92e84f2/src/libstd/panicking.rs:297
      std::panicking::try
             at rustc/5c1f21c3b82297671ad3ae1e8c942d2ca92e84f2/src/libstd/panicking.rs:274
      std::panic::catch_unwind
             at rustc/5c1f21c3b82297671ad3ae1e8c942d2ca92e84f2/src/libstd/panic.rs:394
      std::rt::lang_start_internal
             at rustc/5c1f21c3b82297671ad3ae1e8c942d2ca92e84f2/src/libstd/rt.rs:51
  14: main
  15: __libc_start_main
  16: _start

Thread 'main' panicked at 'Critical database eror: Custom { kind: Other, error: Error { message: "Corruption: Bad table magic number: expected 9863518390377041911, found 0 in /node/chains/bifrost_testnet/db/098270.sst" } }', /rustc/5c1f21c3b82297671ad3ae1e8c942d2ca92e84f2/src/libstd/macros.rs:16

This is a bug. Please report it at:

        https://github.com/bifrost-finance/bifrost/issues/new

**Comment by Dengjianping** [comment]
Hi, it looks that the error was from RocksDB.
could you paste your environment, such as rust(stable/nightly), which branch, OS, etc.
