### ISSUE TITLE
Yoken not transferred 

### ISSUE THREAD

**Issue by nandanvik** [bifrost-finance/bifrost#377]
![20211023_203902](https://user-images.githubusercontent.com/93084347/138670868-4ea5ec38-279f-4d72-95f2-02733d589916.jpg)

Why it happened where is token. And why I did not received it or reverted back.
Subscane team told me to contact you.

**Comment by 0xYancy** [comment]
@Vishwa0405 What is the point of your question? Can you describe it in more detail? Now I only see that you have a BNC balance, I don’t know your question.

**Comment by nandanvik** [comment]
I had transferred BNC token from polkawallet to gate.io wallet but I did not recived it in my gate.io wallet and it is withdrawn from polkawallet. Now subscene showing only balance. 

Where is token and when and how did I recive them in one of my wallet?
