### ISSUE TITLE
Node synchronization is slow and sometimes stops in a block for a long time

### ISSUE THREAD

**Issue by COLUD4** [bifrost-finance/bifrost#414]
![截屏2021-11-25 上午11 40 55](https://user-images.githubusercontent.com/21240219/143375980-eea9a67f-31b0-4b42-b72f-f85c07058cc1.png)

**Comment by ark930** [comment]
Hi, it seems your node a bad p2p connection caused by some known issue, please try to add `--state-cache-size 0` to your startup parameters. Hope it will fix your problem.
