### ISSUE TITLE
InsufficientBalance when bridging BNC

### ISSUE THREAD

**Issue by mostimasblunderbuss** [bifrost-finance/bifrost#490]
I'm trying to replicate the Acala -> Bifrost bridge that took place last September locally (https://acala.discourse.group/t/open-hrmp-cross-chain-communication-between-bifrost-and-karura-parachain/316/3). My set-up script is here: https://github.com/0xmostima/parachain-launch/blob/master/config_mix.yml

When Bifrost processes the received XCM messages (sent from Alice from Acala depositing BNC into Alice at Bifrost), it throws the error `InsufficientBalance`: 

https://github.com/bifrost-finance/bifrost/blob/e0142e611c03fc0a3a2cd26f477342959160a922/pallets/bridge-iost/src/lib.rs#L528

Any clues as to why is this the case? Alice in Bifrost should have enough BNC balance both for existential deposit and BuyExecution.

**Comment by liaopeiyuan** [comment]
here are the debug logs:

<img width="1189" alt="Screen Shot 2022-02-05 at 8 41 11 PM" src="https://user-images.githubusercontent.com/34192321/152664833-8580bf15-0ad8-4c07-a2cd-593377e3057e.png">

**Comment by mostimasblunderbuss** [comment]
here are the error logs 

<img width="1189" alt="Screen Shot 2022-02-05 at 8 41 11 PM" src="https://user-images.githubusercontent.com/91517378/152664860-751aa88b-8bb4-45a6-9da5-cc3d70b6654f.png">

**Comment by herryho** [comment]
> I'm trying to replicate the Acala -> Bifrost bridge that took place last September locally (https://acala.discourse.group/t/open-hrmp-cross-chain-communication-between-bifrost-and-karura-parachain/316/3). My set-up script is here: https://github.com/0xmostima/parachain-launch/blob/master/config_mix.yml
> 
> When Bifrost processes the received XCM messages (sent from Alice from Acala depositing BNC into Alice at Bifrost), it throws the error `InsufficientBalance`:
> 
> https://github.com/bifrost-finance/bifrost/blob/e0142e611c03fc0a3a2cd26f477342959160a922/pallets/bridge-iost/src/lib.rs#L528
> 
> Any clues as to why is this the case? Alice in Bifrost should have enough BNC balance both for existential deposit and BuyExecution.

Since cross-chain transfers utilizes reserve-transfer model, make sure you transfer  BNC first from Bifrost to Karura, so that there are enough BNCs in the Kararua parachain account. Only in that case, you can transfer BNCs from Karura to Bifrost. Also pay attention to the existential deposit requirement to the parachain accounts too.

**Comment by mostimasblunderbuss** [comment]
i see. is there an easy way to transfer BNC into a parachain sovereign account on Bifrost (say, Karura which is 2000 in my example)? Should I use the tokens extrinsics?

**Comment by herryho** [comment]
Karura parachain account in Bifrost chain is  eLHN5PnBeMhxk9Me7BR7QnY3n4qp9hhdEY9Z9QhWV8DK7kL
You can transfer some BNCs directly into this account.
Or you can transfer some BNCs from any personal account in Bifrost to any personal account in Karura.
Both ways can populate Karura parachain account with BNCs.

> i see. is there an easy way to transfer BNC into a parachain sovereign account on Bifrost (say, Karura which is 2000 in my example)? Should I use the tokens extrinsics?

**Comment by mostimasblunderbuss** [comment]
thanks! How did you arrive at the value? Is there a way to replicate it so that I could get the sovereign account for arbitrary parachains connecting to other parachains?

**Comment by herryho** [comment]
karura parachain hex:
hex = "0x7369626cd0070000000000000000000000000000000000000000000000000000"
Hex representation of the word “sibl" is:
 stringToHex(“sibl") = 0x7369626c
Hex representation of parachain id 2000 is 07d0，so its little edian encoding should be d007.
Concat "sibl" hex and chain id hex together, with enough 0s appending to the tail.
Convert the hex representation to ss58 format. Then you can get the parachain account.

> thanks! How did you arrive at the value? Is there a way to replicate it so that I could get the sovereign account for arbitrary parachains connecting to other parachains?

**Comment by mostimasblunderbuss** [comment]
thanks! this is super helpful!
