### ISSUE TITLE
Thread 'tokio-runtime-worker' panicked at 'Storage root must match that calculated.'

### ISSUE THREAD

**Issue by kamiloski88** [bifrost-finance/bifrost#507]
version: Bifrost v0.9.30-RC5
After start service I got an error
`Thread 'tokio-runtime-worker' panicked at 'Storage root must match that calculated.', /root/.cargo/git/checkouts/substrate-7e08433d4c370a21/4aeb95f/frame/executive/src/lib.rs:488
`

**Comment by ark930** [comment]
You can try purge chain and re-sync from scratch.
