### ISSUE TITLE
Introduction on boot asgrad cc3 in docker

### ISSUE THREAD

**Issue by jiqiang90** [bifrost-finance/bifrost#58]
Hi how do i boot local biforst asgard cc3 node in docker? I didn't find the introduction here but I tried to use command as follow 

`
docker pull bifrostnetwork/bifrost:asgard-v0.5.0
docker run -p 9944:9944 bifrostnetwork/bifrost:asgard-v0.5.0 --
`
However, I got 0 peers and 0 block finalized. Please help.

**Comment by Dengjianping** [comment]
Sorry for that, the CC3 session has been closed, there might be few nodes still running, I'm not for sure these standalone nodes are authoring block.

But we have launched a nightly testnet recently, so you pull this image:
```shell
docker pull bifrostnetwork/bifrost:asgard-nihglty
```
And run it like this:
```
docker run -it -p 30333:30333 -p 9944:9944 -p 9933:9933 bifrostnetwork/bifrost:asgard-nihglty --name "NodeName" --rpc-cors 'all' --unsafe-ws-external --rpc-methods 'Unsafe' --unsafe-rpc-external --validator

```
Tip: you can replace NodeName with any string.
