### ISSUE TITLE
Not able to deploy ink smart contract on Bifrost.

### ISSUE THREAD

**Issue by puneet166** [bifrost-finance/bifrost#613]
Hi team , please help me regarding it . 
There is no option of contract in developer section of polkadot Ui -  "https://parachains.info/details/sakura".

So ,  you guys explain? how could i deploy ink smart contract on bifrost para-chain.

**Comment by ark930** [comment]
Hi, you must have mistaken the project, Bifrost does not currently support smart contracts.
