### ISSUE TITLE
InvalidConfiguration "Column config mismatch for column 4"

### ISSUE THREAD

**Issue by stakeworks** [bifrost-finance/bifrost#679]
**Description**
After upgrade from version 0.9.43 to 0.9.52 node failed to start with error:
Error: Service(Other("Scale codec deserialization error: InvalidConfiguration(\"Column config mismatch for column 4. Expected \\\"preimage: false, uniform: false, refc: false, compression: 0, ordered: true\\\", got \\\"preimage: false, uniform: false, refc: false, compression: 0, ordered: false\\\"\")"))

**Environment**
Operating system: Ubuntu 22.04 LTS
bifrost 0.9.52-unknown

**Additional Information**
Node is run with "**--database paritydb**" for parachain and relaychain!
A second node without "--database paritydb" had no problems

**Comment by ark930** [comment]
This issue is related to the polkadot-v0.9.25 version, you can refer to the release note to fix it. https://github.com/paritytech/polkadot/releases/tag/v0.9.25

**Comment by stakeworks** [comment]
Fix worked, thanks.
