### ISSUE TITLE
cannot create module: compilation settings are not compatible with the native host

### ISSUE THREAD

**Issue by kamiloski88** [bifrost-finance/bifrost#692]
Im trying to update my node (bifrost kusama) from 0.9.48 to **any higher** vesrion but after restart my service, got an error. I have update my node multiple times without any problems, but now I dont have any idea whats is wrong, that I cant update my node (im using binary)
`Aug 03 15:36:06 bifrost metabase[734015]: 2022-08-03 15:36:06 [Parachain🌈] Essential task txpool-background failed. Shutting down service.
Aug 03 15:36:06 bifrost metabase[734015]: 2022-08-03 15:36:06 [Parachain🌈] Essential task transaction-pool-task-1 failed. Shutting down service.
Aug 03 15:36:06 bifrost metabase[734015]: 2022-08-03 15:36:06 [Parachain🌈] Essential task transaction-pool-task-0 failed. Shutting down service.
Aug 03 15:36:06 bifrost metabase[734015]: Error: Service(Client(RuntimeApiError(Application(VersionInvalid("cannot create module: compilation settings are not compatible with the native host")))))
Aug 03 15:36:06 bifrost systemd[1]: bifrost.service: Main process exited, code=exited, status=1/FAILURE
Aug 03 15:36:06 bifrost systemd[1]: bifrost.service: Failed with result 'exit-code'.
Aug 03 15:36:06 bifrost systemd[1]: bifrost.service: Scheduled restart job, restart counter is at 8.`

**Comment by Akagi201** [comment]
Could you provide your linux os version and libc version your binary is running?

**Comment by kamiloski88** [comment]
Im running my node on https://www.ovhcloud.com/en/bare-metal/rise/rise-game-2/ using proxmod
My linux:
```
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=20.04
DISTRIB_CODENAME=focal
DISTRIB_DESCRIPTION="Ubuntu 20.04.4 LTS"
```
Im not sure that I did it proper but to check libcversion i used command `ldd --version`
and this is restults
```
jaszczomp@astar:~/Astar/target/release$ ldd --version
ldd (Ubuntu GLIBC 2.31-0ubuntu9.9) 2.31

```
after run `sudo apt install libc-bin`
I got
```
Reading state information... Done
libc-bin is already the newest version (2.31-0ubuntu9.9).
libc-bin set to manually installed.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
```
so its a newlest one

What is interesting on 2nd VM (proxmod) im running bifrost node and during update this node I have very sililar problem/error
