### ISSUE TITLE
About CC4-Flexable Fee

### ISSUE THREAD

**Issue by Cy-zhen** [bifrost-finance/bifrost#75]
## About Support users to use multiple payment fees
The video shows that other tokens will not be consumed as GAS in case of insufficient ASG.Dissatisfied: if the balance is insufficient, it will be automatically postponed to the next currency set and Support users to pay fees in multiple currencies, and users can pay fees freely even if they do not have BNC in their accounts.
Click the image below to jump to the video 👇 
<a href="https://youtu.be/jLZbYvdFuVU" target="_blank"><img  width="200px" src="https://raw.githubusercontent.com/Cy-zhen/MEME/main/Pic/Bifrost_black.jpg"  /></a>

## About Support user to define the currency order used for commission payment
ASG can only be used as the first payment method.
Changing the order of payment causes an error.
Dissatisfied: Support user to define the currency order used for commission payment.
Click the image below to jump to the video 👇 
<a href="https://youtu.be/RQd8gdlYZG8" target="_blank"><img  width="200px" src="https://raw.githubusercontent.com/Cy-zhen/MEME/main/Pic/Bifrost_white.jpg"  /></a>

**Comment by wodlj1314** [comment]
We're figuring out of it, thanks for feedback.
