### ISSUE TITLE
钱包历史记录里看不到交易过的记录

### ISSUE THREAD

**Issue by protonmailv5** [bifrost-finance/bifrost#78]
![211111](https://user-images.githubusercontent.com/61324752/114665564-c8a1c200-9d2f-11eb-86bb-11b746f64f4d.jpg)

如图所示，看不到历史交易记录。

**Comment by Cy-zhen** [comment]
看得到的,换个浏览器或者刷新一下
<img src="https://raw.githubusercontent.com/Cy-zhen/MEME/main/Pic/BifrostWallet-History.png">
