### ISSUE TITLE
UI BUG When the wallet drop-down list is too long, you will not be able to select the address at the bottom

### ISSUE THREAD

**Issue by atinst** [bifrost-finance/bifrost#83]
When the wallet drop-down list is too long, you will not be able to select the address at the bottom, you will not be able to scroll down, it will be bounced back.
<img width="794" alt="WX20210417-021402@2x" src="https://user-images.githubusercontent.com/32417799/115067123-0dda1580-9f23-11eb-9995-d4b7d361dc59.png">

**Comment by wodlj1314** [comment]
> When the wallet drop-down list is too long, you will not be able to select the address at the bottom, you will not be able to scroll down, it will be bounced back.
> <img alt="WX20210417-021402@2x" width="794" src="https://user-images.githubusercontent.com/32417799/115067123-0dda1580-9f23-11eb-9995-d4b7d361dc59.png">

thanks for your feedback, we'll upgrade it.
