### ISSUE TITLE
slippage calculation seems off on dapp

### ISSUE THREAD

**Issue by gilescope** [bifrost-finance/bifrost#840]
When I put in 1000ksm rather than 100ksm then I'm getting a lot of slippage (if I did the trade) but it's showing less than 6 per cent slippage. Definitely doesn't look right to me. If the pool was big enough then 24,000 tether would be about right. Can you have a look - Karura / Basalisk seem to have got it right if you want to crib on their swap pages as comparisons.

With kind regards,

Giles

![image](https://user-images.githubusercontent.com/803976/205352423-b8897888-bc79-42c7-85c9-620c6ae65709.png)

**Comment by gilescope** [comment]
(This was on the kusama relay chain not the polkadot one fyi)

**Comment by killbond007** [comment]
Hi @gilescope ,yeah I fixex it .
