### ISSUE TITLE
Potential issue in farming pallet

### ISSUE THREAD

**Issue by gregdhill** [bifrost-finance/bifrost#866]
You modify the `PalletInfos` storage map in-place [here](https://github.com/bifrost-finance/bifrost/blob/8ba865a266298a16902200c836ac81b3aebd7c97/pallets/farming/src/lib.rs#L256) but as per [this comment](https://github.com/paritytech/substrate/blob/ea387c634715793f806286abf1e64cabf9b7026f/frame/support/src/storage/mod.rs#L273-L274) you may get undefined results doing so.

**Comment by yooml** [comment]
Got it.

**Comment by yooml** [comment]
We only modify the existing values ​​of the map, it should be safe. Look [here](https://substrate.stackexchange.com/a/4466/2424)
