### ISSUE TITLE
 version 'GLIBC_2.32' not found after update collator to version >  0.9.66 

### ISSUE THREAD

**Issue by kamiloski88** [bifrost-finance/bifrost#886]
Hi I have problem I cant update my collator from 0.9.66 to the higher version.
After run newer version i get an error:
`-- Logs begin at Mon 2022-12-12 05:01:16 UTC. --
Jan 28 21:16:02 bifrost metabase[344639]: /home/jaszczomp/bifrost_mainnet/bifrost: /lib/x86_64-linux-gnu/libc.so.6: version 'GLIBC_2.32' not found (required by /home/jaszczomp/bifrost_mainnet/bifrost)
Jan 28 21:16:02 bifrost metabase[344639]: /home/jaszczomp/bifrost_mainnet/bifrost: /lib/x86_64-linux-gnu/libc.so.6: version 'GLIBC_2.33' not found (required by /home/jaszczomp/bifrost_mainnet/bifrost)
Jan 28 21:16:02 bifrost metabase[344639]: /home/jaszczomp/bifrost_mainnet/bifrost: /lib/x86_64-linux-gnu/libc.so.6: version 'GLIBC_2.34' not found (required by /home/jaszczomp/bifrost_mainnet/bifrost)
Jan 28 21:16:02 bifrost systemd[1]: bifrost.service: Main process exited, code=exited, status=1/FAILURE
Jan 28 21:16:02 bifrost systemd[1]: bifrost.service: Failed with result 'exit-code'.
Jan 28 21:16:02 bifrost systemd[1]: bifrost.service: Scheduled restart job, restart counter is at 5.
Jan 28 21:16:02 bifrost systemd[1]: Stopped Bifrost Collator.
Jan 28 21:16:02 bifrost systemd[1]: bifrost.service: Start request repeated too quickly.
Jan 28 21:16:02 bifrost systemd[1]: bifrost.service: Failed with result 'exit-code'.
Jan 28 21:16:02 bifrost systemd[1]: Failed to start Bifrost Collator.`

My OS:
`No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.5 LTS
Release:	20.04
Codename:	focal`

How to solve it?

**Comment by ark930** [comment]
Sorry for the trouble. The native version of bifrost-0.9.69 is compiled based on Ubuntu 22.04 platform. So solution is, 
1. Compile from source code on Ubuntu 20.04
2. Run bifrost-0.9.69 on Ubuntu 22.04

In addition, we will consider restoring the native version based on the Ubuntu 20.04 platform in the next version.
