### ISSUE TITLE
Protocol fee may be wrong

### ISSUE THREAD

**Issue by gregdhill** [bifrost-finance/bifrost#892]
This is currently set to `15` on Bifrost (Kusama) which would only give 1/16 of the 30-basis-point fees earned by liquidity providers (according to the Uniswap v2 whitepaper - section 2.4).

See: https://github.com/zenlinkpro/Zenlink-DEX-Module/issues/62

**Comment by OmniaFlux** [comment]
Thank you very much for your Issue, the author of this document did misunderstand the fee.
